apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-claim
  namespace: prac2-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi