apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pvc
  namespace: prac2-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data